enum proto_types { BOOL, BYTES, DOUBLE, FLOAT, INT64, SINT32, STRING, UINT32 }

enum sila_types {
  BOOL,
  COMMAND_CONFIRM,
  COMMAND_EXEC_UUID,
  DATE,
  DURATION,
  EXEC_ERROR,
  EXEC_INFO,
  EXEC_INFO_COMMAND_STATUS,
  FRAMEWORK_ERROR,
  FRAMEWORK_ERROR_TYPE,
  INTEGER,
  REAL,
  READ_ERROR,
  SILA_ERROR,
  SMALL_BINARY,
  STRING,
  TIME,
  TIMESTAMP,
  TIMEZONE,
  VALIDATION_ERROR
}